key_name = "Test"
app_file = "/Users/sathyanarayanan/Desktop/Assignment-web/app.py"
private_key_path = "/Users/sathyanarayanan/Desktop/TeXX.pem"
new_relic_license_key = "eu01xxbbb98af6d0b9065449b3d3deXXXXXXXX"
new_relic_account_id = "10065218XX"
newrelic_ini_path = "/Users/sathyanarayanan/Desktop/newrelic-1.ini"
